# Remote action to execute e2e functional tests

name: E2E Functional Tests

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs: 
      branch: 
        description: 'Branch to use when running functional tests'
        required: false
        default: 'feature/iam' # update this to main once feature/iam is merged to main
      id:
        description: 'Identifier for the run'
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  functional-test:
    # The type of runner that the job will run on
    runs-on: macos-11

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    - name: ${{ github.event.inputs.id }}
      run: echo Run Identifier is ${{ inputs.id }}
      
    - name: Checkout
      uses: actions/checkout@v2.4.0
      with:
        ref: ${{ github.event.inputs.branch }}
    
    # Runs a single command using the runners shell
    - name: Execute functional tests
      run: make functional-test
